# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Summer Reading Group
tagline:             'Data Science Lab'
description:         '<a href="" target="_blank">Summer reading group</a>, part of  <a href="" target="_blank">Data Science Lab</a> at <a href="" target="_blank">ECpE Department</a>, <a href="" target="_blank">Iowa State University</a>.'
url:                 http://virajshah018.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Data Science Lab
  url:               http://home.engineering.iastate.edu/~chinmay/index.html
  email:             viraj@iastate.edu

# Custom vars
version:             1.0.0
